name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify Ubuntu version explicitly to avoid surprises

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    # Set up JDK 17 (use your desired JDK version)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Use the correct JDK distribution

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Deploy to Heroku
      if: success()  # Only deploy if tests pass
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh  # Install Heroku CLI
        echo "machine api.heroku.com" > ~/.netrc
        echo "login ${HEROKU_EMAIL}" >> ~/.netrc  # Use your Heroku email
        echo "password ${HEROKU_API_KEY}" >> ~/.netrc  # Use your Heroku API key from GitHub secrets
        git remote add heroku https://git.heroku.com/mockingtest.git  # Set Heroku app remote (replace 'mockingtest' with your app's name)
        git push heroku master  # Push to Heroku (use 'master' if that's your default branch)
    
