name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Adjust this to your Java version
        distribution: 'adoptopenjdk'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Deploy to Heroku
      if: success()  # Only deploy if tests pass
      run: |
        git remote add heroku https://git.heroku.com/mockingtest.git
        git push heroku master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Use your Heroku API key stored as a GitHub secret
